### PR TITLE
Unified tab complete

### PR DESCRIPTION
**Pull request by rgbkrk**
```
pd (TAB)
  -->
```

unified-tab-complete

Combines introspection and tab completion in a unified menu.

### CODE REVIEW

**Comment by jdfreder** [comment]
Is the idea that the up/down arrow would cycle through help?  I like it!

**Comment by rgbkrk** [comment]
> Is the idea that the up/down arrow would cycle through help? I like it!

Yup!

**Comment by rgbkrk** [comment]
The introspection bits come back as a mimebundle while the tab completion is a list.

**Comment by Carreau** [comment]
Sweet ! Can you add the line we are completing above ? I like something like the following where `|` is the cursor.

```
numpy.hitog #missing `s` on purpose
```

and the completion would actually show in bold what have been matched.

> **hi**s**tog**ram(a, bins=10, range=None, normed=False, weights=None, density=None)

And would show (when possible) the function signature, even if it does **not** insert it.
That would be useful for julia, where the "help" pard depend on the types of the arguments.

**Comment by rgbkrk** [comment]
> and the completion would actually show in bold what have been matched.

Ooooh I like that a lot!

**Comment by rgbkrk** [comment]
Added the line in above, though not in the graphic itself.

**Comment by Carreau** [comment]
Extra: The completion mechanisme should be able to hint at a cursor position/selection after the completion is picked. Example, where `|` are the position of the anchor and head of the selection:

```python
np.histogram(x, y, b<tab>) 
np.histogram(x, y, bins=|50|)
```

**Comment by rgbkrk** [comment]
Can we do that with the current message spec?

**Comment by Carreau** [comment]
Metadata Babe.

**Comment by rgbkrk** [comment]
Ah yeah, I want that too @Carreau.

**Comment by Carreau** [comment]
I just realized that now Chrome dev tool also completer from history with a chevron icon, which is damned useful:

screen shot 2016-05-06 at 11 16 52

**Comment by rgbkrk** [comment]
Oooh, yeah I saw that too. Chevron for "you previously used this at the console" and the others for active completions.

**Pull request merged**
