### PR TITLE
Sticky cell interface

### PR DESCRIPTION
**Pull request by jdfreder**
There's been a long standing demand in the Jupyter notebook for
sticky cell support.  That is, users want to be able to pin
cells somewhere within view so they remain visible while scrolling
through the document.

This mock suggests a pin UI button be added to the cell toolbar.

sticky

When a cell is pinned, it will appear in a pane that floats
independent of the scroll position of the document.

stickied

Although the mock above shows the hover region vertically above
the document, I think there's reason to investigate it being to
the side of the document instead.  Benifits to a side by side
layout include the ability for the floating area to occupy more
vertical space.

Related:  
- https://github.com/nteract/nteract/issues/431  
- jupyter/notebook#1116

### CODE REVIEW

**Comment by jdfreder** [comment]
cc @rgbkrk @captainsafia

**Comment by rgbkrk** [comment]
Might as well try for the in place vertical hover for now and see what people think of it.

**Comment by rgbkrk** [comment]
You're going to laugh that I'm saying this now - the lock is a bit ambiguous. I'd go for a thumbtack/pushpin icon. Like pinning a notecard up on the wall while you're working in a notebook.

**Comment by rgbkrk** [comment]
I'm amused we didn't have `.jpg` in Git LFS, so these aren't tracked the same as our other binaries here.

**Comment by jdfreder** [comment]
> I'd go for a thumbtack/pushpin icon. Like pinning a notecard up on the wall while you're working in a notebook.

Man, that's what I was looking for in the material icon set!!  We will have to get the thumbtack pushpin icon elsewhere.  I agree, it's definitely the right icon to use.

**Comment by rgbkrk** [comment]
We could replace the material UI icons with [octicons](https://octicons.github.com/), which does have a pin. It also has triangle-right for play/run, `<>` for code, chevrons for folding up input/output areas, _as well as_ a bona fide Markdown icon. It would also give us access to icons for git related actions too.

**Comment by jdfreder** [comment]
> We could replace the material UI icons with octicons, which does have a pin. It also has triangle-right for play/run, <> for code, chevrons for folding up input/output areas, as well as a bona fide Markdown icon. It would also give us access to icons for git related actions too.

I'm really +1 to this after checking them out!  The git actions are a major selling point for me because of future plans for nteract....

**Comment by rgbkrk** [comment]
We took pinned cells out on the latest release because it was turning into a maintenance burden. I'd really love for it to get revisited again.

**Comment by qzcool** [comment]
Hope to see her soon.

**Comment by mnsrmov** [comment]
Is this feature still missing or am I blind or something?

**Comment by rgbkrk** [comment]
This feature was taken out in 2018.

**Pull request merged**
